### PR TITLE
mes-2607-businessNameNowShowsInCandidateDetails

### PR DESCRIPTION
**Pull request by amobarak**
## Description

Adding the business name to the candidate details modal.

## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [x] One review from each scrum team
- [x] Squashed commit contains the JIRA ticket number

### CODE REVIEW

**Comment by TomBillingtonUK** [comment]
Can we have a screenshot please :)

**Review by szabikr — COMMENTED** [review]
Can we have description please?

**Review by TomBillingtonUK — APPROVED** [review]
Looks Good :)

**Review by rossfauldsbjss — APPROVED** [review]
looks good.

**Comment by amobarak** [comment]
Simulator Screen Shot - iPad Pro (10 5-inch) - 2019-09-27 at 13 46 15

**Pull request merged**
