### PR TITLE
MES-3798: Getting rid of nested combined reducers

### PR DESCRIPTION
**Pull request by szabikr**
## Description

Getting rid of nested combined reducers as we are not using it anymore

## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

### CODE REVIEW

**Review by rossfauldsbjss — APPROVED** [review]
was nothing actually using it?
looks good.

**Review by MarkPatt89 — APPROVED** [review]

**Review by TomBillingtonUK — COMMENTED** [review]
You need to update package lock file

**Comment by TomBillingtonUK** [comment]
@Ross - we were using it but the latest store refactoring has allowed us to flatten the reducers so we aren’t nesting them any more. For example a Journal Data reducer has been added so we don’t nest those reducers in the tests.cat-b.reducer.ts

**Comment by ross** [comment]
I think you want @rossfauldsbjss rather than @ross 😁

**Review by rstepnowski — APPROVED** [review]

**Pull request merged**
