### PR TITLE
MES 4160 Cat B+E Test Report Vehicle Checks Scoring

### PR DESCRIPTION
**Pull request by Cullima**
## Description
- Created new Vehicle Checks Cat B+E Test Report Component
- Added new component to B+E test report
- Unit testing 
- Fixed alignment issue with normal start labels

## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [x] One review from each scrum team
- [x] Squashed commit contains the JIRA ticket number

## Screenshots
Screenshot 2019-11-29 at 12 47 05

Screenshot 2019-11-28 at 17 14 30

### CODE REVIEW

**Review by szabikr — APPROVED** [review]

**Comment by szabikr** [comment]
Just built your implementation to an iPad and looks like the vehicle checks competency button is disabled which is good, but also needs greyed out slightly. Use Miro as design reference.

**Comment by TomBillingtonUK** [comment]
> Just built your implementation to an iPad and looks like the vehicle checks competency button is disabled which is good, but also needs greyed out slightly. Use Miro as design reference.

The abstract which contains the design for this + the css is - https://app.goabstract.com/projects/53fd5dd0-1391-11e9-bf74-5b3f3cb661bc/branches/master/collections/d980cd44-5f04-49fd-9a8a-9cdadda21b81?collectionLayerId=27cca7d5-63de-4e19-a021-de4760f3eade&mode=build&selected=1816547392-AFAA2FCA-71A4-433F-A28C-3DC37493A948


I normally find it easier then miro

**Comment by Cullima** [comment]
> Just built your implementation to an iPad and looks like the vehicle checks competency button is disabled which is good, but also needs greyed out slightly. Use Miro as design reference.

Thanks both. Have updated PR with backgroud colour from Abstract

**Review by rossfauldsbjss — APPROVED** [review]
Looks good

**Pull request merged**
