### PR TITLE
PR Template Update

### PR DESCRIPTION
**Pull request by TomBillingtonUK**
## Description and relevant Jira numbers
- Updated the PR Template

## Pull Request checklist:

- [ ] [WIP] tag removed from PR title
- [ ] PR has an understandable description

## Git feature branch checklist:

- [ ] branch name comply with our branching strategy
- [ ] git branch contains relevant JIRA ticket number
- [ ] branch rebased against the latest develop
- [ ] commits are squashed

## Sign off process checklist:

- [ ] Code has been tested manually
- [ ] Tests are passing
- [ ] PR link added to JIRA
- [ ] Reviewers selected in Github
- [ ] Any new reusable component/widget added to component library on Confluence

- [ ] Screenshot(s) captured on the physical device (if applicable)
- [ ] Tested by QA
- [ ] PO's approval

### CODE REVIEW

**Review by MarkPatt89 — APPROVED** [review]
Less is more. Love it.

**Review by amobarak — APPROVED** [review]
Nice !

**Review by roberthall12 — APPROVED** [review]

**Comment by roberthall12** [comment]
May be worth adding in something like `JIRA Ticket: https://jira.dvsacloud.uk/browse/MES-xxxx`

**Review by szabikr — APPROVED** [review]
Would be nice to go down to only the 5 most important checkboxes. But we can easily change it in the future. Let's see how good this is

**Review by buzzub — COMMENTED** [review]
I like it. I think this is the minimum number of things we need.

**Review by ammarhaiderbjss — APPROVED** [review]
Much better thank you 👍

**Review by rstepnowski — APPROVED** [review]

**Pull request merged**
