### PR TITLE
Technical debt transmission component re used

### PR DESCRIPTION
**Pull request by appleabs**
Existing technical debt - Transmission Field, We should have one for all pages/cats.
Ensures only one transmission component is used across pass-finalisation, waiting-room-to-car and non-pass-finalisation pages. Transmission component now in the common components folder so can be accessed in multiple categories.
## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

### CODE REVIEW

**Review by TomBillingtonUK — APPROVED** [review]
Nice Job :)

**Review by szabikr — APPROVED** [review]
Looks good

**Review by ammarhaiderbjss — APPROVED** [review]
😍 Superb!

**Review by rossfauldsbjss — APPROVED** [review]
looks good

**Pull request merged**
