### PR TITLE
MES-1801 Fixed font update bug on app first launch

### PR DESCRIPTION
**Pull request by roberthall12**
## Description and relevant Jira numbers
Fixed the bug where the font wasn't updating to the accessibility settings on first launch.
https://jira.i-env.net/browse/MES-1801

## Pull Request checklist:

- [x] [WIP] tag removed from PR title
- [x] PR has an understandable description

## Git feature branch checklist:

- [x] branch name comply with our branching strategy
- [x] git branch contains relevant JIRA ticket number
- [ ] branch rebased against the latest develop
- [x] commits are squashed

## Sign off process checklist:

- [x] Code has been tested manually
- [x] Tests are passing
- [x] PR link added to JIRA
- [x] Reviewers selected in Github
- [ ] Any new reusable component/widget added to component library on Confluence

- [ ] Screenshot(s) captured on the physical device (if applicable)
- [x] Tested by QA
- [ ] PO's approval

### CODE REVIEW

**Comment by buzzub** [comment]
I think this will conflict with the class based method of increasing text size. From what I understood, this is like pressing CMD + in Chrome and simply zooms the webview. Combined with the class based approach to increasing text size this will double the zoom effect.

This would mean that the test report page would have all elements zoomed when this is not intended.

Could you check whether this is the case?

**Comment by roberthall12** [comment]
> I think this will conflict with the class based method of increasing text size. From what I understood, this is like pressing CMD + in Chrome and simply zooms the webview. Combined with the class based approach to increasing text size this will double the zoom effect.
> 
> This would mean that the test report page would have all elements zoomed when this is not intended.
> 
> Could you check whether this is the case?



> I think this will conflict with the class based method of increasing text size. From what I understood, this is like pressing CMD + in Chrome and simply zooms the webview. Combined with the class based approach to increasing text size this will double the zoom effect.
> 
> This would mean that the test report page would have all elements zoomed when this is not intended.
> 
> Could you check whether this is the case?

I don't think so, I believe it just updates the locally stored IOS zoom setting that the app uses so this shouldn't conflict with the resizing class. It was just the textZoom variable that wasn't being updated. Is there any way I can test on screens other than the journal?

**Comment by buzzub** [comment]
The zoom level on the waiting room or test report page shouldn't change, so you could test that

**Comment by roberthall12** [comment]
Tested on waiting room page and no change in font size. Can't seem to navigate to test report page in the app.

**Pull request merged**
