### PR TITLE
Feature/mes 4669 mod2 category selection

### PR DESCRIPTION
**Pull request by edwardwilson**
## Description
Added the change category selector into the Mod2 WRTC page following the implementation for Mod1.

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)
image

### CODE REVIEW

**Review by MarkPatt89 — APPROVED** [review]

**Review by Cullima — CHANGES_REQUESTED** [review]
Think you need to update tests.effects to stop the populate test action from being fired on starting the test from the journal. This is how it was done for mod 1.

**Comment by edwardwilson** [comment]
That is changing in a future PR as the change in tests.effects breaks the analytics. The fix for mod1 fixes it for all of them

**Comment by Cullima** [comment]
> That is changing in a future PR as the change in tests.effects breaks the analytics. The fix for mod1 fixes it for all of them



> That is changing in a future PR as the change in tests.effects breaks the analytics. The fix for mod1 fixes it for all of them

Ah, ok. Does the page still present the button only prior to the category being confirmed? This was the reason for not dispatching the action initially. I think the idea is the user is forced to open the modal and confirm the category.

**Comment by edwardwilson** [comment]
> > That is changing in a future PR as the change in tests.effects breaks the analytics. The fix for mod1 fixes it for all of them
> 
> > That is changing in a future PR as the change in tests.effects breaks the analytics. The fix for mod1 fixes it for all of them
> 
> Ah, ok. Does the page still present the button only prior to the category being confirmed? This was the reason for not dispatching the action initially. I think the idea is the user is forced to open the modal and confirm the category.

Right now the page loads with an existing selection. So it doesn't show the Button to select, only the option to change. In commit https://github.com/dvsa/mes-mobile-app/commit/b1a334cfd74d8cf34c49ccf63f9403d604c9c11c the changes to the bike category component can be seen which introduces the new functionality.

I don't think we should hold this PR up while we wait for the other changes to get merged. We can review the story after to confirm the AC has been met later

**Review by Cullima — APPROVED** [review]

**Pull request merged**
