### PR TITLE
Ensure that examiner staff number is copied into test state to make test submission valid

### PR DESCRIPTION
**Pull request by johnmorleybjss**
* Relates to https://jira.i-env.net/browse/MES-2295
* `staffNumber` needs to be included in the submission payload to be saved into the Aurora record
* Ensure that we populate it when starting a test
* **Needs confirmation of behaviour when we start a test while in unauthenticated mode**

## Pull Request checklist:

- [x] [WIP] tag removed from PR title
- [x] PR has an understandable description

## Git feature branch checklist:

- [x] branch name comply with our branching strategy
- [x] git branch contains relevant JIRA ticket number
- [x] branch rebased against the latest develop
- [x] commits are squashed

## Sign off process checklist:

- [ ] Code has been tested manually
- [x] Tests are passing
- [ ] PR link added to JIRA
- [ ] Reviewers selected in Github
- [ ] Any new reusable component/widget added to component library on Confluence

- [ ] Screenshot(s) captured on the physical device (if applicable)
- [ ] Tested by QA
- [ ] PO's approval

### CODE REVIEW

**Comment by ammarhaiderbjss** [comment]
> Needs confirmation of behaviour when we start a test while in unauthenticated mode
Does this mean we're not sure how this is meant to work in unauthenticated mode?

**Comment by johnmorleybjss** [comment]
Yes @ammarhaiderbjss, this isn't tested yet. It could be that we need to start maintaining the staff number in the journal for subsequent copy into the test - this would require poller changes. Was thinking that we could possibly merge this to get us moving again on submission for the meantime.

**Comment by ammarhaiderbjss** [comment]
> Yes @ammarhaiderbjss, this isn't tested yet. It could be that we need to start maintaining the staff number in the journal for subsequent copy into the test - this would require poller changes. Was thinking that we could possibly merge this to get us moving again on submission for the meantime.

Ok cool happy to approve, re maintaining staff number from journal: that's an interesting one. I would have considered the staff number from Azure AD rather than the journal to be the source of truth when it comes to identifying who submitted a test.

**Comment by johnmorleybjss** [comment]
Discussed with @rstepnowski, we are planning to annotate the journal with the logged in staff number and store it in the app state at the time of retrieval from the backend. Unless we can retrieve the staff number from authenticator while in unauthenticated mode. This needs more investigation, so a ticket will be created to address. Merging this interim solution to get the online submission working for now.

**Pull request merged**
