### PR TITLE
Adding vehicle details

### PR DESCRIPTION
**Pull request by MarkPatt89**
## Description and relevant Jira numbers

- Display vehicle details on the journal page.

## Pull Request checklist:

- [x] [WIP] tag removed from PR title
- [ ] PR has an understandable description

## Git feature branch checklist:

- [x] branch name comply with our branching strategy
- [x] git branch contains relevant JIRA ticket number
- [x] branch rebased against the latest develop
- [x] commits are squashed

## Sign off process checklist:

- [x] Code has been tested manually
- [x] Tests are passing
- [ ] PR link added to JIRA
- [ ] Reviewers selected in Github
- [ ] Any new reusable component/widget added to component library on Confluence

- [ ] Screenshot(s) captured on the physical device (if applicable)
- [ ] Tested by QA
- [ ] PO's approval

Screenshot 2019-05-03 at 13 35 19

### CODE REVIEW

**Comment by buzzub** [comment]
The reason these were removed is that the accessibility design for larger and extra large typer meant there was no room on the row. Will be worth running this by Nad. 

Also, I think as a team we need to have a think about accessibility and how we're bearing that in mind (or not) when coding page layouts.

**Comment by MarkPatt89** [comment]
@buzzub yeah I'm aware of the layout issues. Andy is chatting to the POs on Tuesday about this. They don't want truncation but I'll make sure Nad is aware of any conversations that take place.

**Comment by szabolcs-keresztes** [comment]
@MarkPatt89 any conclusion on this PR?

**Comment by MarkPatt89** [comment]
@szabolcs-keresztes not as yet. Still pending a discussion with Nad.

**Pull request closed without merging**
