### PR TITLE
MES-3553: Handling issue when config url does not exist in mdm config

### PR DESCRIPTION
**Pull request by szabikr**
## Description

Displaying a customised message when remote config url is not present on the mdm config.

## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

IMG_0001

### CODE REVIEW

**Review by TomBillingtonUK — COMMENTED** [review]
Can we have some unit tests :)

**Comment by TomBillingtonUK** [comment]
Also a screenshot of the error page

**Review by buzzub — APPROVED** [review]
Approved, pending shiny unit tests

**Comment by ammarhaiderbjss** [comment]
Closing, this work will be picked up again in https://jira.dvsacloud.uk/browse/MES-3575

**Pull request closed without merging**
