### PR TITLE
MES-3102 - Saving shortName as the tellMeQuestion description

### PR DESCRIPTION
**Pull request by roberthall12**
> ## Description and relevant Jira numbers

- RSIS was complaining that the `tellMeQuestion.description` within the test submission was over 100 characters, so the description is now set as the `tellMeQuestion.shortName` 
https://jira.dvsacloud.uk/browse/MES-3102

## Pull Request checklist:

- [x] [WIP] tag removed from PR title
- [x] PR has an understandable description

## Git feature branch checklist:

- [x] branch name comply with our branching strategy
- [x] git branch contains relevant JIRA ticket number
- [x] branch rebased against the latest develop
- [ ] commits are squashed

## Sign off process checklist:

- [ ] Code has been tested manually
- [ ] Tests are passing
- [ ] PR link added to JIRA
- [ ] Reviewers selected in Github
- [ ] Any new reusable component/widget added to component library on Confluence

- [ ] Screenshot(s) captured on the physical device (if applicable)
- [ ] Tested by QA
- [ ] PO's approval

### CODE REVIEW

**Review by jameshighfield — APPROVED** [review]

**Review by TomBillingtonUK — APPROVED** [review]

**Review by chrisnappin — CHANGES_REQUESTED** [review]
What about show me questions?

**Comment by roberthall12** [comment]
> What about show me questions?

@chrisnappin  the longest description for a show me question is only 87 characters which is within the 100 char limit so would be accepted by RSIS

**Comment by chrisnappin** [comment]
I think we need to handle show me and tell me questions in the same way, and I think the DVSA MI team will think the same.

**Comment by roberthall12** [comment]
> I think we need to handle show me and tell me questions in the same way, and I think the DVSA MI team will think the same.

Okay cool, I'll set the showMeQuestions description to use the shortName as well

**Comment by chrisnappin** [comment]
Brilliant, thanks

**Review by jameshighfield — APPROVED** [review]

**Review by chrisnappin — APPROVED** [review]

**Pull request merged**
