### PR TITLE
Rekey redirect and unit tests

### PR DESCRIPTION
**Pull request by amobarak**
## Description and relevant Jira numbers

Office page redirects to reason for rekey if test is a rekey.
JIRA: https://jira.dvsacloud.uk/browse/MES-3161

## Pull Request checklist:

- [x] [WIP] tag removed from PR title
- [x] PR has an understandable description

## Git feature branch checklist:

- [x] branch name comply with our branching strategy
- [x] git branch contains relevant JIRA ticket number
- [x] branch rebased against the latest develop
- [x] commits are squashed

## Sign off process checklist:

- [x] Code has been tested manually
- [x] Tests are passing
- [ ] PR link added to JIRA
- [ ] Reviewers selected in Github
- [ ] Any new reusable component/widget added to component library on Confluence

- [ ] Screenshot(s) captured on the physical device (if applicable)
- [ ] Tested by QA
- [ ] PO's approval

### CODE REVIEW

**Review by TomBillingtonUK — DISMISSED** [review]
This should be on the office page not back to office

**Comment by amobarak** [comment]
Simulator Screen Shot - iPad Pro (10 5-inch) - 2019-08-13 at 13 04 17

**Review by rossfauldsbjss — APPROVED** [review]
looks good

**Review by roberthall12 — APPROVED** [review]
NIce

**Review by TomBillingtonUK — APPROVED** [review]

**Pull request merged**
